### ISSUE TITLE
Fields with "Text Area" data type no longer editable in the table? 

### ISSUE THREAD

**Issue by lindyrogers** [ericrsmith35/DatatableV3#2]
Not sure when this happened, I've got records with data in the text area field that were created using the datatableV2 in a flow. But now, it seems like if the data type is text area you're unable to inline edit that field from the datatable (V2 or Version 3.0.6). Nothing has changed with field level security on this field (and the flow runs in system context without sharing anyway). Anyone else having this problem? From what I can tell, I've got all of the setup like it needs to be, editing is enabled for the column etc., but maybe I'm overlooking something!

**Comment by ericrsmith35** [comment]
I made a change to support rich text area fields that turned off editing.  Are you looking to only edit plain text area fields?

**Comment by lindyrogers** [comment]
Yes it's just a plain text area.

**Comment by ericrsmith35** [comment]
This has been corrected in the latest release.  v3.0.10  2/27/21
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/
