### ISSUE TITLE
Configure columns error

### ISSUE THREAD

**Issue by fefris** [ericrsmith35/DatatableV3#4]
When clicking on Configure columns button, get a spinner and then a broken link image and the following error when pressing X to close window.

Uncaught TypeError: Cannot read property 'forEach' of undefined throws at https://xxxxx.lightning.force.com/auraFW/javascript/AE898lCB2KpCUerBipCwXg/aura_prod.js:12:29357

Both base packs installed, permissions assigned. 

Previous v2 and v1 table components also in org.

**Comment by ericrsmith35** [comment]
Please review the final tip here: https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/#Restrictions
