### ISSUE TITLE
No option to clear selection on single select

### ISSUE THREAD

**Issue by anthony-grantbook** [ericrsmith35/DatatableV3#5]
Where I have a single select column, and I am **not** requiring the user to select a value, it would be great to have the option to clear the values from the table. At the moment the only option is to go back a step to clear the values when I return

**Comment by anthony-grantbook** [comment]
the clear button is available if there is only 1 option in the table, but if there are multiple then it is not available

**Comment by ericrsmith35** [comment]
Could you please post some images of what you are trying to do?

**Comment by ericrsmith35** [comment]
Also, make sure you are using the latest version of Datatable and you have this option cleared in the Table Behavior section.
![image](https://user-images.githubusercontent.com/24724447/143275493-053b2b5b-38ef-4bf6-9e04-cbef15246acd.png)
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2

**Comment by anthony-grantbook** [comment]
thanks @ericrsmith35 

Here's some more info - from what I can tell if there is only 1 value in the collection then it appears, otherwise it doesn't. I've worked around it with the checkbox underneath, and I am on 3.2.2

**Table 1 Settings**
![image](https://user-images.githubusercontent.com/46610339/143276275-36a0ce22-c467-471c-89a8-21e305bd1988.png)

**Table 1 Debug**
![image](https://user-images.githubusercontent.com/46610339/143276584-bea9ab4e-2819-4747-92f2-af506ff28674.png)

**Table 2 Settings**
![image](https://user-images.githubusercontent.com/46610339/143276456-b8544e64-48dc-49c8-a1a7-42438e1536a8.png)

**Table 2 Debug**
![image](https://user-images.githubusercontent.com/46610339/143276655-f3e4af8c-d81d-4eb8-931b-7b3283ebef23.png)

**Comment by emtrav64** [comment]
I am facing this same issue, did you find a solution?

**Comment by ericrsmith35** [comment]
This has been addressed in the latest release: v3.4.5
https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/#Installation
